### ISSUE TITLE
XCTest/XCTest.h file not found

### ISSUE THREAD

**Issue by donileo** [sweetmandm/ionicons-iOS#25]
Im getting the above compile time error simply when using ionicons pod. The error is located in file ioniconTests.m line #9. If I remove the tests file from the compile sources the error goes away. Seems this issue is new as I was previously using ionicons perfectly fine.

**Comment by sweetmandm** [comment]
Hm, I imagine this is likely an issue with this line in the pod spec:
https://github.com/sweetmandm/ionicons-iOS/blob/master/ionicons.podspec#L12
which may include this file by accident, but instead of using the current pattern should either explicitly require the relevant files or ignore the tests directory.

**Comment by donileo** [comment]
Makes sense!

**Comment by sweetmandm** [comment]
Closing since this should be fixed in https://github.com/sweetmandm/ionicons-iOS/pull/26
